name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/tmdwns2595/ }}
          TIMEZONE: Asia/Seoul
